### PR TITLE
Changed For Redirecting..

### PR DESCRIPTION
**Pull request by WarFade**

### CODE REVIEW

**Comment by StarkBotsIndustries** [comment]
Does `t.me` links not work in your country?

**Comment by WARFADE-BOSS** [comment]
> Does `t.me` links not work in your country?



> Does `t.me` links not work in your country?

It works but not in chrome or any browser
It just works in the app itself

**Comment by WARFADE-BOSS** [comment]
> Watch this video below
> 
> * if you have a web login only then both links were open in the web only
> * if you have desktop/app only then both were open in desktop/app
> * if both then you have choice
> 
> ezgif com-gif-maker [ ](https://user-images.githubusercontent.com/89268060/171255229-5a5bf8c2-c61a-4996-93d7-91c309e24617.gif) ezgif com-gif-maker [ ](https://user-images.githubusercontent.com/89268060/171255229-5a5bf8c2-c61a-4996-93d7-91c309e24617.gif)

Bruh
Don't make a serious issue 
It's just a correction to old readme

If u want to do then you can do by urself
I don't want to be in collaboration
I just added a correction where old t.me link don't open in phone's
You can change it to telegram.me or telegram.dog
It would be probably better if i created issue rather than pull request

**Comment by Designatory** [comment]
Yeah you are right, you should do this in issues instead of PRs

**Pull request closed without merging**
